### ISSUE TITLE
ds-dev crashes when folder it's watching is emptied

### ISSUE THREAD

**Issue by teleclimber** [teleclimber/Dropserver#20]
```
panic: Rel: can't make . relative to /Users/ollie/Documents/Code/Leftovers/app/.git

goroutine 6 [running]:
main.(*DevAppWatcher).ignorePath(0xc0000af4a0, 0x47ae5c6, 0x1, 0x4995ac0)
	/Users/ollie/Documents/Code/DropServer/cmd/ds-dev/appwatcher.go:146 +0x11b
main.(*DevAppWatcher).watchDir.func1(0x47ae5c6, 0x1, 0x4999a90, 0xc0004bca90, 0x0, 0x0, 0x0, 0xc000445e00)
	/Users/ollie/Documents/Code/DropServer/cmd/ds-dev/appwatcher.go:129 +0x2af
path/filepath.walk(0x47ae5c6, 0x1, 0x4999a90, 0xc0004bca90, 0xc000445ed8, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:418 +0xe7
path/filepath.Walk(0x47ae5c6, 0x1, 0xc000445ed8, 0x4999a90, 0xc0004bc680)
	/usr/local/go/src/path/filepath/path.go:501 +0x113
main.(*DevAppWatcher).watchDir(0xc0000af4a0, 0x47ae5c6, 0x1, 0xc0004bc680, 0x0)
	/Users/ollie/Documents/Code/DropServer/cmd/ds-dev/appwatcher.go:124 +0x5d
main.(*DevAppWatcher).watch.func1(0xc00006e240, 0xc0000af4a0)
	/Users/ollie/Documents/Code/DropServer/cmd/ds-dev/appwatcher.go:97 +0x1ca
created by main.(*DevAppWatcher).watch
	/Users/ollie/Documents/Code/DropServer/cmd/ds-dev/appwatcher.go:84 +0xbc
```

This happens whenever I run a build process that deletes everything the app's frontend dir.

**Comment by teleclimber** [comment]
Fixed in 9292040944baa0ffb44c90a57e78f3a02077f17a
